### ISSUE TITLE
Exposed envs

### ISSUE THREAD

**Issue by taylorosbourne** [SeansC12/blog#1]
Hey @SeansC12 you should delete this repo.  You have checked in your .env files.

**Comment by huncyrus** [comment]
Yeah, delete it, and don't forget to delete all the instances and switch all your passwords around.
Then remove the credentials (you can have a .env.example with just the keys) and please do not your easy guessable passwords (like for MySQL). Consider using a password generator with quite a length and turn on everywhere the 2FA.
Then you should upload the project.

Why is this advice? Because you might end up getting breached, causing a few hundred or thousands of process times on different services (AWS) in very short time (you will be surprised to know, how creative people can be...).

Also, limit your resources if you publish them and run them on AWS or any other cloud provider. Set up limits, alarms, and perhaps some timeframe, how long it should/could run.

**Comment by kxrn0** [comment]
bump

**Comment by SeansC12** [comment]
Hi @taylorosbourne @huncyrus and @kxrn0 , thank you so much for raising this point up and providing valuable feedback and advice for me. I have removed my .envs from this repo. I have also updated all my passwords 🤣 . Rookie mistake haha. Thanks again for your feedback, and have a good day.
